"use client"

import { useState, useEffect, useRef, useCallback, useMemo } from "react"
import { AlertTriangle, ChevronDown, X } from "lucide-react"
import { type Order } from "@/lib/data"
import { fetchRecentOrders, subscribeToOrders, fetchFailedOrders, resolveFailedOrder, type FailedOrder } from "@/lib/orders"
import { printOrder } from "@/lib/thermal-printer"
import { usePrinterConfig } from "@/hooks/use-printer-config"
import { OrderCard } from "@/components/order-card"
import { OrderDetailPanel } from "@/components/order-detail-panel"
import { AdminMenuButton } from "./admin-shell"
import { cn } from "@/lib/utils"

// scheduledTime is always machine-generated by lib/checkout-schedule.ts as
// "{dayLabel} {day} {month} - {slot}", where dayLabel is one of "اليوم",
// "غدًا", or a weekday name (lib/checkout-schedule.ts's DAY_NAMES, same
// order as JS Date.getDay()). We bucket orders by that first word directly
// instead of re-parsing a date out of the label - it's already the exact
// semantic bucket we want, and avoids the year ambiguity a day+month label
// without a year would otherwise create.
const AR_WEEKDAYS = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"]

interface ScheduleBucket {
  key: string
  label: string
  priority: number
}

function getScheduleBucket(order: Order): ScheduleBucket {
  const firstWord = order.scheduledTime?.trim().split(/\s+/)[0]

  if (!firstWord || firstWord === "اليوم") return { key: "today", label: "اليوم", priority: 0 }
  if (firstWord === "غدًا") return { key: "tomorrow", label: "غدًا", priority: 1 }

  const weekdayIndex = AR_WEEKDAYS.indexOf(firstWord)
  if (weekdayIndex !== -1) {
    const todayIndex = new Date().getDay()
    const offset = ((weekdayIndex - todayIndex + 7) % 7) || 7
    return { key: firstWord, label: firstWord, priority: offset }
  }

  // Unrecognized/legacy label - safest default is to surface it today.
  return { key: "today", label: "اليوم", priority: 0 }
}

// Realtime subscription is the primary sync path (subscribeToOrders below).
// This interval is a fallback only, in case the realtime channel silently
// drops - it does not need to run every few seconds.
const ORDERS_POLL_INTERVAL_MS = 60000
const INITIAL_ORDER_HISTORY_DAYS = 365
const INITIAL_ORDER_HISTORY_LIMIT = 5000
const POLL_ORDER_HISTORY_DAYS = 30
const POLL_ORDER_HISTORY_LIMIT = 500

function mergeOrders(existing: Order[], incoming: Order[]): Order[] {
  const merged = new Map<string, Order>()
  for (const order of existing) merged.set(order.id, order)
  for (const order of incoming) merged.set(order.id, order)
  return Array.from(merged.values()).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
}

function failedOrderReasonLabel(reason: string): string {
  if (reason === "rate_limited") return "تم رفض الطلب مؤقتًا (عدد كبير من الطلبات في وقت قصير)"
  if (reason === "invalid_payload") return "بيانات الطلب غير مكتملة أو غير صحيحة"
  if (reason.startsWith("unknown_menu_item")) return "أحد الأصناف لم يعد متوفرًا في القائمة"
  if (reason === "invalid_delivery_area") return "منطقة التوصيل لم تعد صالحة"
  if (reason === "menu_load_failed") return "تعذر تحميل أسعار القائمة"
  if (reason.startsWith("db_insert_failed")) return "خطأ في حفظ الطلب في قاعدة البيانات"
  return reason
}

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([])
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState<string | null>(null)
  const [dayFilter, setDayFilter] = useState<string>("all")
  const [newOrderAlert, setNewOrderAlert] = useState(false)
  const audioRef = useRef<HTMLAudioElement | null>(null)

  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null)
  const [printingOrderId, setPrintingOrderId] = useState<string | null>(null)
  const [printError, setPrintError] = useState<string | null>(null)
  const { config: printerConfig, saveConfig: savePrinterConfig } = usePrinterConfig()

  const [failedOrders, setFailedOrders] = useState<FailedOrder[]>([])
  const [failedOrdersPanelOpen, setFailedOrdersPanelOpen] = useState(false)
  const unresolvedFailedOrders = useMemo(
    () => failedOrders.filter((f) => !f.resolved),
    [failedOrders]
  )

  const refreshFailedOrders = useCallback(async () => {
    try {
      const data = await fetchFailedOrders()
      setFailedOrders(data)
    } catch (error) {
      console.error("Failed to load failed-orders log", error)
    }
  }, [])

  useEffect(() => {
    void refreshFailedOrders()
    const intervalId = window.setInterval(() => void refreshFailedOrders(), ORDERS_POLL_INTERVAL_MS)
    return () => window.clearInterval(intervalId)
  }, [refreshFailedOrders])

  const handleResolveFailedOrder = async (id: string) => {
    setFailedOrders((prev) => prev.map((f) => (f.id === id ? { ...f, resolved: true } : f)))
    const { error } = await resolveFailedOrder(id)
    if (error) {
      setFailedOrders((prev) => prev.map((f) => (f.id === id ? { ...f, resolved: false } : f)))
      window.alert(`تعذر تعليم الطلب كمُعالَج، حاول مرة أخرى (${error})`)
    }
  }

  const playNotificationSound = useCallback(() => {
    if (!audioRef.current) return
    audioRef.current.currentTime = 0
    audioRef.current.play().catch(() => {})
  }, [])

  const refreshOrders = useCallback(async (mode: "initial" | "poll" = "poll") => {
    try {
      const data = await fetchRecentOrders(
        mode === "initial"
          ? { days: INITIAL_ORDER_HISTORY_DAYS, maxRecords: INITIAL_ORDER_HISTORY_LIMIT }
          : { days: POLL_ORDER_HISTORY_DAYS, maxRecords: POLL_ORDER_HISTORY_LIMIT }
      )
      setOrders((prev) => mergeOrders(prev, data))
      setLoadError(null)
    } catch (error) {
      console.error("Failed to refresh admin orders", error)
      setLoadError("تعذر تحميل الطلبات من لوحة التحكم. تحقق من الجلسة أو إعدادات Supabase ثم أعد المحاولة.")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void refreshOrders("initial")
  }, [refreshOrders])

  useEffect(() => {
    const intervalId = window.setInterval(() => {
      void refreshOrders("poll")
    }, ORDERS_POLL_INTERVAL_MS)

    const handleWindowFocus = () => {
      void refreshOrders("poll")
    }

    const handleVisibilityChange = () => {
      if (!document.hidden) {
        void refreshOrders("poll")
      }
    }

    window.addEventListener("focus", handleWindowFocus)
    document.addEventListener("visibilitychange", handleVisibilityChange)

    return () => {
      window.clearInterval(intervalId)
      window.removeEventListener("focus", handleWindowFocus)
      document.removeEventListener("visibilitychange", handleVisibilityChange)
    }
  }, [refreshOrders])

  useEffect(() => {
    const cleanup = subscribeToOrders(
      (newOrder) => {
        setOrders((prev) => mergeOrders(prev, [newOrder]))
        setNewOrderAlert(true)
        playNotificationSound()
        setTimeout(() => setNewOrderAlert(false), 2500)
      },
      (id, status) => {
        setOrders((prev) => prev.map((o) => (o.id === id ? { ...o, status } : o)))
      }
    )
    return () => cleanup?.()
  }, [playNotificationSound])

  const handlePrint = useCallback(async (order: Order) => {
    setPrintingOrderId(order.id)
    setPrintError(null)
    try {
      await printOrder(order, { ip: printerConfig.ip })
    } catch (err) {
      setPrintError(err instanceof Error ? err.message : "فشل الاتصال بالطابعة")
    } finally {
      setPrintingOrderId(null)
    }
  }, [printerConfig.ip])

  const filterTabs = useMemo(() => {
    const byKey = new Map<string, { key: string; label: string; priority: number; count: number }>()
    for (const order of orders) {
      const bucket = getScheduleBucket(order)
      const existing = byKey.get(bucket.key)
      if (existing) {
        existing.count += 1
      } else {
        byKey.set(bucket.key, { ...bucket, count: 1 })
      }
    }
    const days = Array.from(byKey.values())
      .sort((a, b) => a.priority - b.priority)
      .slice(0, 4)
    return [{ key: "all", label: "الكل", priority: -1, count: orders.length }, ...days]
  }, [orders])

  const filteredOrders = useMemo(() => {
    const out = dayFilter === "all" ? orders.slice() : orders.filter((order) => getScheduleBucket(order).key === dayFilter)
    out.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
    return out
  }, [orders, dayFilter])

  return (
    <>
      <audio ref={audioRef} preload="auto">
        <source src="data:audio/wav;base64,UklGRnoGAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQoGAACBhYqFbF1fdJivrJBhNjVgodDbq2EcBj+a2teleGZwzOrl0LFwRD9iq+Xx8duSQAYvh9vw+/zhok4bG33Q6Pn/+eapV0M+cLzg8P/+9u64cTg5eMDg8f7+9O++fUMvZ7be9P/96fLMj0MjV6rc8v7+5u3SlGFDM2Cp4fH++OTt2aFzTSlbqNvx/vjh7d+rfFwyU57W7v/64+zisYRkNUSRzun//eDq5buPc0Y+hMPl/v3c5ufAmoJXOHi72/v92uLnyqKPZTtqr9P4/trg5tGtm3REXaLK8v7Z3eTYuKh/ST5rr9Ly/tjb4tzDtJNfPmau0PD+1tnf4M3AoHhEP2iv0PD91dbd5NXJq4JMPWWt0PD91NTb5trQtI1UPWSuzfD909Pa5+DXv5xiP2Ss0O/809HX5+Te0MJzQl2ny+/9z87U6Ojl2s2CRlihxu390c3S6Ovq4NiXTFCXvOz8z8vQ5+3v6eTglVdLkbbm+szIzePv8+7s6apkR4OqrOrIxcne8fb07u+7dUx3l6bjxcPF2fP6+PT11od0Wmahz8XBwdXy/v338N2dg29SYJLCwb+/0fP///nz5q+Wf2xXYo64v7+/y+/////579+7pI53ZmV3qLm9vsPQ7P7///zz6se4rJaEeHNxlam2ur7E0On6///68+nXyrq0ppqMg3t3fZamsbW6wMnX6vr//fXp3NPJwbuwpZuQh4F+gI6cpq+2vcTM1eLy/v3x5NvTzca/ubKroZiPiIWDhouXoqq0vMPKz9bh7vj89uvf19HOyMS+t7GsppyTi4eFhomSmqSvuMDIzdLZ4+v2+/Pn3dXPy8bBvLazrKiflo+KhoaIjZainrG7w8rQ1t3l7vf78ePZ0szIw7+6trKuqaOdlo+LiYmMkJmjrri/xs3T2eHo8Pn67+TZ0s7Jxb+7t7OvrqqmoJqUj4uKi42SnKewtb3EytHX3+bt9vnu49nSzMnFwLy4tK+sqKSfm5aPjYuLjZGYoKmyusDGzNLZ4Ofs9frw5dzVz8vGwr66trKuqqainJeRjo2MjpGXn6iwuL/Gys/W3eTo8Pf67OLa1M/Lxr+8uLSwr6ynop2YlJCOjY6RlZyjq7O6wcfN0djf5u3z+PHn39nTz8rFwLy4tLCsqaWgnZiUkI6Oj5KYn6ess7q/xs3P1dri5+3y9O7m4NjSzcnFv7u3sq6rp6OgnZmVkpCPkJOXnaOqsLe9xMrP1Nrf5u3y9O/n4dvVz8rFwLq3s6+rp6OgnJiVkpCQkZSZnqSqsLe+w8nO09je5Ors8/Tu5+Hb1c/KxL65tLCsqKSgnZmVko+QkZSYnqSqs7e+w8jO0tfe5Ors8vPu5+Hb1c/KxL65tLCsqKSgnZmVkpCQkZSYnqSqsLe9w8jO0tfe5Onr8vPu5+Dc1tDKxL65tLCsqKSgnJmVkpCQkZSYnqSqsLe9w8jN0tfe5Onr8fLu5+Dc1tDKxL65tLCsp6SgnJmVkpCQkZSYnqOqsLa9w8jN0tbd5Onr8fLu5uDc1tDKxL65tK+sp6SgnJmVkpCQkZSYnqOpsLa9wsjN0tXd5Onr8fHu5uDb1tDKxL64tK+sp6OgnJmVko+PkZSYnqOpsLa8wsjN0tXc5Ojr8fHu5uDb1c/JxL64s6+sp6OgnJiVko+PkZSYnaOpsLa8wsfM0dXc5Ojr8PHt5uDb1c/JxL64s6+rp6OgnJiVko+PkZOYnaOpsLW8wsfM0dXc4+jr8PHt5d/a1c/JxL64s6+rpqKfnJiVko+PkJOXnaOosbW8wsfM0dXc4+jr8PHt5d/a1c/Jw764s6+rpqKfnJiUkY+OkJOXnaOosLW7wsfL0NXc4+jr7/Ht5d/a1M/Jw724sq6rpqKenJiUkY+OkJOXnKOosLW7wsbL0NTc4ujq7/Ds5d/a1M/Jw724sq6rpqKenJiUkY6OkJOXnKKnsLW7wsbL0NTb4ujq7/Ds5N/Z1M7Iw724sq6qpqGenJeUkY6NkJOWnKKnr7W7wsbK0NTb4ujq7+/s5N/Z1M7Iwr24sq6qpqGenJeUkY6NkJOWnKKnr7S7wMbKz9Pb4efp7+/s5N7Z1M7Iwr24sa6qpaGenJeUkI6NkJOWm6Knr7S6wMbKz9Pa4efp7+/r5N7Y087Hwr24sa6qpaGenJeUkI6NkJOWm6GnrrS6wMXKz9Pa4Ofp7u7r5N7Y087Hwr24sa6qpaGenJeUkI6NkJOWm6GnrrS6wMXJztPa4Ofp7u7r49/YD87Hwr24sa6qpaGenJeUkI6NkJOWm6GnrrS5wMXJztLZ4Obp7u3r493Xz8zGwby3sa6ppaCdm5eUkI6NkJOWm6CmrrO5wMXJztLZ3+bo7e3r493Xz8zGwLy3sa6ppaCdm5eUkI2NkJKVm6CmrrO5v8XJzdLZ3+bo7e3q493X0MzGwLy3sa2ppaCdm5aUkI2Nj5KVm6CmrbO5v8TJzdLY3+bo7ezq493X0MvGwLy3sK2po5+dm5aUkI2Nj5KVmqClrbO4v8TIzNHY3uXn7ezq4t3X0MvFwLy2sK2po5+dmpaTkI2Nj5KVmqClrbK4v8TIzNHY3uXn7ezq4t3W0MvFv7u2sK2oo5+dmpaTkI2Mj5KVmqClrLK4vsPI" type="audio/wav" />
      </audio>

      {newOrderAlert ? (
        <div className="fixed left-4 right-4 top-4 z-50 rounded-2xl bg-admin-ink p-4 text-white shadow-xl md:left-auto md:w-96">
          <p className="font-bold">طلب جديد</p>
          <p className="text-sm opacity-90">تم استقبال طلب جديد في لوحة الطلبات</p>
        </div>
      ) : null}

      <div className="sticky top-0 z-20 flex items-center justify-between gap-3 border-b border-admin-border-soft bg-admin-header px-4 py-3 sm:px-8">
        <div className="flex min-w-0 flex-1 gap-0.5 overflow-x-auto">
          {filterTabs.map((tab) => (
            <button
              key={tab.key}
              type="button"
              onClick={() => setDayFilter(tab.key)}
              className={cn(
                "flex flex-shrink-0 items-center gap-1.5 whitespace-nowrap rounded-[7px] px-3.5 py-2 font-sans text-[13px] font-semibold transition-colors",
                dayFilter === tab.key ? "bg-admin-ink text-white" : "text-admin-muted hover:bg-black/5"
              )}
            >
              {tab.label}
              <span className="font-admin-mono text-[11px] opacity-60">{tab.count}</span>
            </button>
          ))}
        </div>
        <AdminMenuButton />
      </div>

      <div className="mx-auto max-w-[1600px] px-4 pb-16 pt-7 sm:px-8">
        {unresolvedFailedOrders.length > 0 ? (
          <div className="mb-4 overflow-hidden rounded-2xl border border-red-200 bg-red-50">
            <button
              type="button"
              onClick={() => setFailedOrdersPanelOpen((v) => !v)}
              className="flex w-full items-center justify-between gap-2 px-4 py-3 text-right"
            >
              <div className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 shrink-0 text-red-500" />
                <span className="text-sm font-bold text-red-700">
                  {unresolvedFailedOrders.length} طلب لم يتم حفظه — راجع واتساب للتأكد منه
                </span>
              </div>
              <ChevronDown
                className={cn("h-4 w-4 text-red-500 transition-transform", failedOrdersPanelOpen && "rotate-180")}
              />
            </button>
            {failedOrdersPanelOpen ? (
              <div className="divide-y divide-red-100 border-t border-red-200">
                {unresolvedFailedOrders.map((f) => (
                  <div key={f.id} className="flex items-start justify-between gap-3 px-4 py-3 text-right text-sm">
                    <div className="min-w-0 flex-1">
                      <p className="font-semibold text-gray-900">
                        {f.customerName || "بدون اسم"}
                        {f.customerPhone ? ` · ${f.customerPhone}` : ""}
                      </p>
                      <p className="mt-0.5 text-gray-500">{failedOrderReasonLabel(f.reason)}</p>
                      <p className="mt-0.5 text-xs text-gray-400">
                        {f.createdAt.toLocaleString("ar-SA", { dateStyle: "medium", timeStyle: "short" })}
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => void handleResolveFailedOrder(f.id)}
                      className="shrink-0 rounded-full border border-gray-300 px-3 py-1.5 text-xs font-semibold text-gray-600 hover:bg-gray-100"
                    >
                      تم الحل
                    </button>
                  </div>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {loading ? (
          <div className="py-16 text-center">
            <p className="text-admin-muted">جاري تحميل الطلبات...</p>
          </div>
        ) : loadError && orders.length === 0 ? (
          <div className="py-16 text-center">
            <X className="mx-auto mb-4 h-8 w-8 text-red-400" />
            <p className="mx-auto max-w-md text-sm font-medium text-red-600">{loadError}</p>
            <button
              onClick={() => void refreshOrders()}
              className="mt-4 rounded-xl bg-admin-ink px-4 py-2 text-sm font-semibold text-white"
            >
              إعادة المحاولة
            </button>
          </div>
        ) : filteredOrders.length === 0 ? (
          <div className="py-16 text-center">
            <p className="text-admin-muted">لا توجد طلبات</p>
          </div>
        ) : (
          <>
            {loadError ? (
              <div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-right text-sm text-amber-700">
                {loadError}
              </div>
            ) : null}
            <div className="grid grid-cols-[repeat(auto-fill,minmax(320px,1fr))] gap-5">
              {filteredOrders.map((order) => (
                <OrderCard
                  key={order.id}
                  order={order}
                  onOpen={setSelectedOrder}
                  onPrint={handlePrint}
                  printing={printingOrderId === order.id}
                />
              ))}
            </div>
          </>
        )}
      </div>

      <OrderDetailPanel
        order={selectedOrder}
        onOpenChange={(open) => {
          if (!open) setSelectedOrder(null)
        }}
        onPrint={handlePrint}
        printing={selectedOrder !== null && printingOrderId === selectedOrder.id}
        printError={printError}
        printerIp={printerConfig.ip}
        onSavePrinterIp={(ip) => void savePrinterConfig({ ip })}
      />
    </>
  )
}
